### ISSUE TITLE
Chess leader board warning system

### ISSUE THREAD

**Issue by abdulshafiq0** [CheAle14/bot-source-code#53]
Dear Mr Alexander Elliot CHESSter II
Could you please add a warning system into the chess leader board for any misuse where:

 - The extra wins/loses are removed and give the victim of the crime point (5?)
-  If it is the first offence then give a warning with no other punishments
- if it is the second offence then reset them back to 100 points
- if it is the third offence then kick them out of chess club for a month
- any more offence after that then kick them out permanently
         
Thank you
Abdul Shafiq

**Comment by CheAle14** [comment]
Alternative idea:
How about limiting the number of games a person can play in one day?
It is unrealistic for a person to play aganist the same person more than once in a day

**Comment by CheAle14** [comment]
actually im retarded

**Comment by CheAle14** [comment]
that was a really shit idea

**Comment by abdulshafiq0** [comment]
But if someone us really bad they may lose quickly and there is no one else to play so they play the same person twice.
And an offender can just make them win against a random person

**Comment by CheAle14** [comment]
The issue is due to the score: Whilst it might be technically possible to revert the exact score gained, i am not currently saving that data. It would require an addition to the amount of things i save, which, due to disk space storage limits, is not something i am looking to add.
Perhaps a more simple thing: 
First offence removes the win/loss change and drops them by one position at least (with manual intervention used if they were known to be lower)
Second offence can then reset them entirely

**Comment by abdulshafiq0** [comment]
how about for first offence you just add more wins /loses so the aggregate score becomes the same
and for second offence reset them

**Comment by CheAle14** [comment]
If the win was gained via invalid purposes, then it would be more logical to simply remove the win rather than add one to the loser to offset.

**Comment by CheAle14** [comment]
https://github.com/CheAle14/bot-source-code/blob/master/src/RESTAPI/Functions/HTML/Chess.cs#L423
This is where the web page calls when you finish a match

**Comment by CheAle14** [comment]
```
        int getKFunction(ChessPlayer a)
        {
            int total = a.Wins + a.Losses;
            if (total <= 3)
                return 40;
            if (total > 3 && total <= 6)
                return 30;
            if (total > 6 && total <= 10)
                return 20;
            return 10;
        }

        double getExpectedRating(ChessPlayer a, ChessPlayer b)
        {
            var denom = 1 + (Math.Pow(10, (b.Rating - a.Rating) / 400d));
            return 1 / denom;
        }

        double getRating(ChessPlayer a, ChessPlayer b, double actualScore)
        {
            var update = getKFunction(a) * (actualScore - getExpectedRating(a, b));
            return a.Rating + update;
        }
```
These are the maths functions that calculate the score that should be changed

**Comment by CheAle14** [comment]
Expressed as maths,on wikipedia:
![image](https://user-images.githubusercontent.com/12370876/70536890-7e1a9f00-1b57-11ea-965f-d35a940cd0f7.png)

**Comment by CheAle14** [comment]
Should deduct/add points simply via the k-function calculation.
We will need to count number of games played up to the invalid game and feed that into the k-function and use that as worst case scenario

**Comment by abdulshafiq0** [comment]
dont include invalid games in the k function

**Comment by abdulshafiq0** [comment]
only count valid games

**Comment by abdulshafiq0** [comment]
take / add the maximum

**Comment by CheAle14** [comment]
Closed due to:
a) Out of date, this idea is precluded by the introduction of the "Conduct" rules and that system of corrective measures
b) In the wrong place: this issue is in regards to changing the terms, which should occur [over there](https://github.com/CheAle14/chess-terms/issues)
