### ISSUE TITLE
Sort by win rate

### ISSUE THREAD

**Issue by abdulshafiq0** [CheAle14/bot-source-code#54]
Dear Mr Alexander Eliott CHESSter III
         I am writing to inform you of a proposal that i had whereas when points are uniform that the table is sorted on win percentage

I look forward to hearing from you soon
Yours Sincerely
         Abdul Shafiq

**Comment by CheAle14** [comment]
Closing due to idea being accepted and implemented.
Leaderboard is sorted as follows:
```csharp
Players.OrderByDescending(x => x.Rating)
    .ThenByDescending(x => x.WinRate)
    .ThenByDescending(x => x.Wins + x.Losses))
```
